// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: event_access_permission.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventAccessPermissionResponse_AccessType int32

const (
	EventAccessPermissionResponse_allow EventAccessPermissionResponse_AccessType = 0 // 允许执行
	EventAccessPermissionResponse_deny  EventAccessPermissionResponse_AccessType = 1 // 禁止执行
)

// Enum value maps for EventAccessPermissionResponse_AccessType.
var (
	EventAccessPermissionResponse_AccessType_name = map[int32]string{
		0: "allow",
		1: "deny",
	}
	EventAccessPermissionResponse_AccessType_value = map[string]int32{
		"allow": 0,
		"deny":  1,
	}
)

func (x EventAccessPermissionResponse_AccessType) Enum() *EventAccessPermissionResponse_AccessType {
	p := new(EventAccessPermissionResponse_AccessType)
	*p = x
	return p
}

func (x EventAccessPermissionResponse_AccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventAccessPermissionResponse_AccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_access_permission_proto_enumTypes[0].Descriptor()
}

func (EventAccessPermissionResponse_AccessType) Type() protoreflect.EnumType {
	return &file_event_access_permission_proto_enumTypes[0]
}

func (x EventAccessPermissionResponse_AccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventAccessPermissionResponse_AccessType.Descriptor instead.
func (EventAccessPermissionResponse_AccessType) EnumDescriptor() ([]byte, []int) {
	return file_event_access_permission_proto_rawDescGZIP(), []int{2, 0}
}

type EventAccessPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName   string     `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventTime   uint64     `protobuf:"varint,2,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	EventDetail *anypb.Any `protobuf:"bytes,3,opt,name=eventDetail,proto3" json:"eventDetail,omitempty"`
}

func (x *EventAccessPermission) Reset() {
	*x = EventAccessPermission{}
	mi := &file_event_access_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAccessPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAccessPermission) ProtoMessage() {}

func (x *EventAccessPermission) ProtoReflect() protoreflect.Message {
	mi := &file_event_access_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAccessPermission.ProtoReflect.Descriptor instead.
func (*EventAccessPermission) Descriptor() ([]byte, []int) {
	return file_event_access_permission_proto_rawDescGZIP(), []int{0}
}

func (x *EventAccessPermission) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventAccessPermission) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *EventAccessPermission) GetEventDetail() *anypb.Any {
	if x != nil {
		return x.EventDetail
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActName  string `protobuf:"bytes,1,opt,name=act_name,json=actName,proto3" json:"act_name,omitempty"`
	ActValue string `protobuf:"bytes,2,opt,name=act_value,json=actValue,proto3" json:"act_value,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_event_access_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_event_access_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_event_access_permission_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetActName() string {
	if x != nil {
		return x.ActName
	}
	return ""
}

func (x *Action) GetActValue() string {
	if x != nil {
		return x.ActValue
	}
	return ""
}

type EventAccessPermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   bool                                     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Access   EventAccessPermissionResponse_AccessType `protobuf:"varint,2,opt,name=access,proto3,enum=docmap.exchange.model.EventAccessPermissionResponse_AccessType" json:"access,omitempty"`
	Bubble   bool                                     `protobuf:"varint,3,opt,name=bubble,proto3" json:"bubble,omitempty"`     // 是否气泡通知
	Desc     string                                   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`          // 策略描述
	PolicyId uint32                                   `protobuf:"varint,5,opt,name=policyId,proto3" json:"policyId,omitempty"` // 策略ID（上报事件时需要附带这个值）
}

func (x *EventAccessPermissionResponse) Reset() {
	*x = EventAccessPermissionResponse{}
	mi := &file_event_access_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAccessPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAccessPermissionResponse) ProtoMessage() {}

func (x *EventAccessPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_access_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAccessPermissionResponse.ProtoReflect.Descriptor instead.
func (*EventAccessPermissionResponse) Descriptor() ([]byte, []int) {
	return file_event_access_permission_proto_rawDescGZIP(), []int{2}
}

func (x *EventAccessPermissionResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *EventAccessPermissionResponse) GetAccess() EventAccessPermissionResponse_AccessType {
	if x != nil {
		return x.Access
	}
	return EventAccessPermissionResponse_allow
}

func (x *EventAccessPermissionResponse) GetBubble() bool {
	if x != nil {
		return x.Bubble
	}
	return false
}

func (x *EventAccessPermissionResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *EventAccessPermissionResponse) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

var File_event_access_permission_proto protoreflect.FileDescriptor

var file_event_access_permission_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x15, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x15, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22,
	0x40, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0xfb, 0x01, 0x0a, 0x1d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x57, 0x0a, 0x06, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3f, 0x2e, 0x64, 0x6f,
	0x63, 0x6d, 0x61, 0x70, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0a,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x65, 0x6e, 0x79, 0x10, 0x01, 0x42,
	0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x65, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_event_access_permission_proto_rawDescOnce sync.Once
	file_event_access_permission_proto_rawDescData = file_event_access_permission_proto_rawDesc
)

func file_event_access_permission_proto_rawDescGZIP() []byte {
	file_event_access_permission_proto_rawDescOnce.Do(func() {
		file_event_access_permission_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_access_permission_proto_rawDescData)
	})
	return file_event_access_permission_proto_rawDescData
}

var file_event_access_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_access_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_event_access_permission_proto_goTypes = []any{
	(EventAccessPermissionResponse_AccessType)(0), // 0: docmap.exchange.model.EventAccessPermissionResponse.AccessType
	(*EventAccessPermission)(nil),                 // 1: docmap.exchange.model.EventAccessPermission
	(*Action)(nil),                                // 2: docmap.exchange.model.Action
	(*EventAccessPermissionResponse)(nil),         // 3: docmap.exchange.model.EventAccessPermissionResponse
	(*anypb.Any)(nil),                             // 4: google.protobuf.Any
}
var file_event_access_permission_proto_depIdxs = []int32{
	4, // 0: docmap.exchange.model.EventAccessPermission.eventDetail:type_name -> google.protobuf.Any
	0, // 1: docmap.exchange.model.EventAccessPermissionResponse.access:type_name -> docmap.exchange.model.EventAccessPermissionResponse.AccessType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_access_permission_proto_init() }
func file_event_access_permission_proto_init() {
	if File_event_access_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_access_permission_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_access_permission_proto_goTypes,
		DependencyIndexes: file_event_access_permission_proto_depIdxs,
		EnumInfos:         file_event_access_permission_proto_enumTypes,
		MessageInfos:      file_event_access_permission_proto_msgTypes,
	}.Build()
	File_event_access_permission_proto = out.File
	file_event_access_permission_proto_rawDesc = nil
	file_event_access_permission_proto_goTypes = nil
	file_event_access_permission_proto_depIdxs = nil
}
