// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: get_tag.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Accurate bool   `protobuf:"varint,2,opt,name=accurate,proto3" json:"accurate,omitempty"`
	Remove   bool   `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"` // 读取完毕立即删除
}

func (x *GetTag) Reset() {
	*x = GetTag{}
	mi := &file_get_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTag) ProtoMessage() {}

func (x *GetTag) ProtoReflect() protoreflect.Message {
	mi := &file_get_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTag.ProtoReflect.Descriptor instead.
func (*GetTag) Descriptor() ([]byte, []int) {
	return file_get_tag_proto_rawDescGZIP(), []int{0}
}

func (x *GetTag) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetTag) GetAccurate() bool {
	if x != nil {
		return x.Accurate
	}
	return false
}

func (x *GetTag) GetRemove() bool {
	if x != nil {
		return x.Remove
	}
	return false
}

type GetTagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath       string `protobuf:"bytes,1,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Tags           []*Tag `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	EntityIdentity string `protobuf:"bytes,3,opt,name=entityIdentity,proto3" json:"entityIdentity,omitempty"` // 客户端无法从tags里获取entityIdentity，所以必须在这里显示传回
	FamilyIdentity string `protobuf:"bytes,4,opt,name=familyIdentity,proto3" json:"familyIdentity,omitempty"` // 同上
	Result         bool   `protobuf:"varint,5,opt,name=result,proto3" json:"result,omitempty"`
	Encrypted      bool   `protobuf:"varint,6,opt,name=encrypted,proto3" json:"encrypted,omitempty"` // 已经被客户端加密过了
}

func (x *GetTagResponse) Reset() {
	*x = GetTagResponse{}
	mi := &file_get_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagResponse) ProtoMessage() {}

func (x *GetTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagResponse.ProtoReflect.Descriptor instead.
func (*GetTagResponse) Descriptor() ([]byte, []int) {
	return file_get_tag_proto_rawDescGZIP(), []int{1}
}

func (x *GetTagResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetTagResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetTagResponse) GetEntityIdentity() string {
	if x != nil {
		return x.EntityIdentity
	}
	return ""
}

func (x *GetTagResponse) GetFamilyIdentity() string {
	if x != nil {
		return x.FamilyIdentity
	}
	return ""
}

func (x *GetTagResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *GetTagResponse) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

var File_get_tag_proto protoreflect.FileDescriptor

var file_get_tag_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x15, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x09, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x58, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0xe2, 0x01, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x6f, 0x63, 0x6d, 0x61,
	0x70, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x65, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_get_tag_proto_rawDescOnce sync.Once
	file_get_tag_proto_rawDescData = file_get_tag_proto_rawDesc
)

func file_get_tag_proto_rawDescGZIP() []byte {
	file_get_tag_proto_rawDescOnce.Do(func() {
		file_get_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_tag_proto_rawDescData)
	})
	return file_get_tag_proto_rawDescData
}

var file_get_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_tag_proto_goTypes = []any{
	(*GetTag)(nil),         // 0: docmap.exchange.model.GetTag
	(*GetTagResponse)(nil), // 1: docmap.exchange.model.GetTagResponse
	(*Tag)(nil),            // 2: docmap.exchange.model.Tag
}
var file_get_tag_proto_depIdxs = []int32{
	2, // 0: docmap.exchange.model.GetTagResponse.tags:type_name -> docmap.exchange.model.Tag
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_get_tag_proto_init() }
func file_get_tag_proto_init() {
	if File_get_tag_proto != nil {
		return
	}
	file_tag_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_tag_proto_goTypes,
		DependencyIndexes: file_get_tag_proto_depIdxs,
		MessageInfos:      file_get_tag_proto_msgTypes,
	}.Build()
	File_get_tag_proto = out.File
	file_get_tag_proto_rawDesc = nil
	file_get_tag_proto_goTypes = nil
	file_get_tag_proto_depIdxs = nil
}
