// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: refresh_pause.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RefreshPause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pause bool `protobuf:"varint,1,opt,name=pause,proto3" json:"pause,omitempty"` // true: 暂停刷新; false: 继续刷新
}

func (x *RefreshPause) Reset() {
	*x = RefreshPause{}
	mi := &file_refresh_pause_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPause) ProtoMessage() {}

func (x *RefreshPause) ProtoReflect() protoreflect.Message {
	mi := &file_refresh_pause_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPause.ProtoReflect.Descriptor instead.
func (*RefreshPause) Descriptor() ([]byte, []int) {
	return file_refresh_pause_proto_rawDescGZIP(), []int{0}
}

func (x *RefreshPause) GetPause() bool {
	if x != nil {
		return x.Pause
	}
	return false
}

type RefreshPauseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succ bool `protobuf:"varint,1,opt,name=succ,proto3" json:"succ,omitempty"` // true: 成功; false: 失败
}

func (x *RefreshPauseResponse) Reset() {
	*x = RefreshPauseResponse{}
	mi := &file_refresh_pause_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPauseResponse) ProtoMessage() {}

func (x *RefreshPauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refresh_pause_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPauseResponse.ProtoReflect.Descriptor instead.
func (*RefreshPauseResponse) Descriptor() ([]byte, []int) {
	return file_refresh_pause_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshPauseResponse) GetSucc() bool {
	if x != nil {
		return x.Succ
	}
	return false
}

var File_refresh_pause_proto protoreflect.FileDescriptor

var file_refresh_pause_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x70, 0x61, 0x75, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x24, 0x0a, 0x0c,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x70, 0x61, 0x75,
	0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x50, 0x61, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75,
	0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x75, 0x63, 0x63, 0x42, 0x19,
	0x5a, 0x17, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_refresh_pause_proto_rawDescOnce sync.Once
	file_refresh_pause_proto_rawDescData = file_refresh_pause_proto_rawDesc
)

func file_refresh_pause_proto_rawDescGZIP() []byte {
	file_refresh_pause_proto_rawDescOnce.Do(func() {
		file_refresh_pause_proto_rawDescData = protoimpl.X.CompressGZIP(file_refresh_pause_proto_rawDescData)
	})
	return file_refresh_pause_proto_rawDescData
}

var file_refresh_pause_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_refresh_pause_proto_goTypes = []any{
	(*RefreshPause)(nil),         // 0: docmap.exchange.model.RefreshPause
	(*RefreshPauseResponse)(nil), // 1: docmap.exchange.model.RefreshPauseResponse
}
var file_refresh_pause_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_refresh_pause_proto_init() }
func file_refresh_pause_proto_init() {
	if File_refresh_pause_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_refresh_pause_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_refresh_pause_proto_goTypes,
		DependencyIndexes: file_refresh_pause_proto_depIdxs,
		MessageInfos:      file_refresh_pause_proto_msgTypes,
	}.Build()
	File_refresh_pause_proto = out.File
	file_refresh_pause_proto_rawDesc = nil
	file_refresh_pause_proto_goTypes = nil
	file_refresh_pause_proto_depIdxs = nil
}
