// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: report_action_event.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportActionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName   string     `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventTime   uint64     `protobuf:"varint,2,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	PolicyId    uint32     `protobuf:"varint,3,opt,name=policyId,proto3" json:"policyId,omitempty"`
	EventDetail *anypb.Any `protobuf:"bytes,4,opt,name=eventDetail,proto3" json:"eventDetail,omitempty"`
}

func (x *ReportActionEvent) Reset() {
	*x = ReportActionEvent{}
	mi := &file_report_action_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportActionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportActionEvent) ProtoMessage() {}

func (x *ReportActionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_report_action_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportActionEvent.ProtoReflect.Descriptor instead.
func (*ReportActionEvent) Descriptor() ([]byte, []int) {
	return file_report_action_event_proto_rawDescGZIP(), []int{0}
}

func (x *ReportActionEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ReportActionEvent) GetEventTime() uint64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

func (x *ReportActionEvent) GetPolicyId() uint32 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *ReportActionEvent) GetEventDetail() *anypb.Any {
	if x != nil {
		return x.EventDetail
	}
	return nil
}

type ReportEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ReportEventResponse) Reset() {
	*x = ReportEventResponse{}
	mi := &file_report_action_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventResponse) ProtoMessage() {}

func (x *ReportEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_action_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventResponse.ProtoReflect.Descriptor instead.
func (*ReportEventResponse) Descriptor() ([]byte, []int) {
	return file_report_action_event_proto_rawDescGZIP(), []int{1}
}

func (x *ReportEventResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_report_action_event_proto protoreflect.FileDescriptor

var file_report_action_event_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x6f, 0x63,
	0x6d, 0x61, 0x70, 0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01,
	0x0a, 0x11, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x0b, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x65,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_report_action_event_proto_rawDescOnce sync.Once
	file_report_action_event_proto_rawDescData = file_report_action_event_proto_rawDesc
)

func file_report_action_event_proto_rawDescGZIP() []byte {
	file_report_action_event_proto_rawDescOnce.Do(func() {
		file_report_action_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_report_action_event_proto_rawDescData)
	})
	return file_report_action_event_proto_rawDescData
}

var file_report_action_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_report_action_event_proto_goTypes = []any{
	(*ReportActionEvent)(nil),   // 0: docmap.exchange.model.ReportActionEvent
	(*ReportEventResponse)(nil), // 1: docmap.exchange.model.ReportEventResponse
	(*anypb.Any)(nil),           // 2: google.protobuf.Any
}
var file_report_action_event_proto_depIdxs = []int32{
	2, // 0: docmap.exchange.model.ReportActionEvent.eventDetail:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_report_action_event_proto_init() }
func file_report_action_event_proto_init() {
	if File_report_action_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_report_action_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_report_action_event_proto_goTypes,
		DependencyIndexes: file_report_action_event_proto_depIdxs,
		MessageInfos:      file_report_action_event_proto_msgTypes,
	}.Build()
	File_report_action_event_proto = out.File
	file_report_action_event_proto_rawDesc = nil
	file_report_action_event_proto_goTypes = nil
	file_report_action_event_proto_depIdxs = nil
}
