// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: submit_usernames.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitUserNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserNames []string `protobuf:"bytes,1,rep,name=userNames,proto3" json:"userNames,omitempty"` // 收集到的用户姓名
}

func (x *SubmitUserNames) Reset() {
	*x = SubmitUserNames{}
	mi := &file_submit_usernames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUserNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUserNames) ProtoMessage() {}

func (x *SubmitUserNames) ProtoReflect() protoreflect.Message {
	mi := &file_submit_usernames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUserNames.ProtoReflect.Descriptor instead.
func (*SubmitUserNames) Descriptor() ([]byte, []int) {
	return file_submit_usernames_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitUserNames) GetUserNames() []string {
	if x != nil {
		return x.UserNames
	}
	return nil
}

type SubmitUserNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 处理结果
}

func (x *SubmitUserNamesResponse) Reset() {
	*x = SubmitUserNamesResponse{}
	mi := &file_submit_usernames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUserNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUserNamesResponse) ProtoMessage() {}

func (x *SubmitUserNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submit_usernames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUserNamesResponse.ProtoReflect.Descriptor instead.
func (*SubmitUserNamesResponse) Descriptor() ([]byte, []int) {
	return file_submit_usernames_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitUserNamesResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_submit_usernames_proto protoreflect.FileDescriptor

var file_submit_usernames_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70,
	0x2e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22,
	0x2f, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x22, 0x31, 0x0a, 0x17, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f,
	0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_submit_usernames_proto_rawDescOnce sync.Once
	file_submit_usernames_proto_rawDescData = file_submit_usernames_proto_rawDesc
)

func file_submit_usernames_proto_rawDescGZIP() []byte {
	file_submit_usernames_proto_rawDescOnce.Do(func() {
		file_submit_usernames_proto_rawDescData = protoimpl.X.CompressGZIP(file_submit_usernames_proto_rawDescData)
	})
	return file_submit_usernames_proto_rawDescData
}

var file_submit_usernames_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_submit_usernames_proto_goTypes = []any{
	(*SubmitUserNames)(nil),         // 0: docmap.exchange.model.SubmitUserNames
	(*SubmitUserNamesResponse)(nil), // 1: docmap.exchange.model.SubmitUserNamesResponse
}
var file_submit_usernames_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_submit_usernames_proto_init() }
func file_submit_usernames_proto_init() {
	if File_submit_usernames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submit_usernames_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_submit_usernames_proto_goTypes,
		DependencyIndexes: file_submit_usernames_proto_depIdxs,
		MessageInfos:      file_submit_usernames_proto_msgTypes,
	}.Build()
	File_submit_usernames_proto = out.File
	file_submit_usernames_proto_rawDesc = nil
	file_submit_usernames_proto_goTypes = nil
	file_submit_usernames_proto_depIdxs = nil
}
