// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: dm_whoami.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DMWhoAmIReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	DeviceId    string `protobuf:"bytes,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
}

func (x *DMWhoAmIReq) Reset() {
	*x = DMWhoAmIReq{}
	mi := &file_dm_whoami_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMWhoAmIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMWhoAmIReq) ProtoMessage() {}

func (x *DMWhoAmIReq) ProtoReflect() protoreflect.Message {
	mi := &file_dm_whoami_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMWhoAmIReq.ProtoReflect.Descriptor instead.
func (*DMWhoAmIReq) Descriptor() ([]byte, []int) {
	return file_dm_whoami_proto_rawDescGZIP(), []int{0}
}

func (x *DMWhoAmIReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DMWhoAmIReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DMWhoAmIReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type DMWhoAmIResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DMWhoAmIResp) Reset() {
	*x = DMWhoAmIResp{}
	mi := &file_dm_whoami_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DMWhoAmIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DMWhoAmIResp) ProtoMessage() {}

func (x *DMWhoAmIResp) ProtoReflect() protoreflect.Message {
	mi := &file_dm_whoami_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DMWhoAmIResp.ProtoReflect.Descriptor instead.
func (*DMWhoAmIResp) Descriptor() ([]byte, []int) {
	return file_dm_whoami_proto_rawDescGZIP(), []int{1}
}

var File_dm_whoami_proto protoreflect.FileDescriptor

var file_dm_whoami_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x6d, 0x5f, 0x77, 0x68, 0x6f, 0x61, 0x6d, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x18, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x63, 0x0a, 0x0b, 0x44,
	0x4d, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64,
	0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x4d, 0x57, 0x68, 0x6f, 0x41, 0x6d, 0x49, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dm_whoami_proto_rawDescOnce sync.Once
	file_dm_whoami_proto_rawDescData = file_dm_whoami_proto_rawDesc
)

func file_dm_whoami_proto_rawDescGZIP() []byte {
	file_dm_whoami_proto_rawDescOnce.Do(func() {
		file_dm_whoami_proto_rawDescData = protoimpl.X.CompressGZIP(file_dm_whoami_proto_rawDescData)
	})
	return file_dm_whoami_proto_rawDescData
}

var file_dm_whoami_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dm_whoami_proto_goTypes = []any{
	(*DMWhoAmIReq)(nil),  // 0: docmap.message.api.model.DMWhoAmIReq
	(*DMWhoAmIResp)(nil), // 1: docmap.message.api.model.DMWhoAmIResp
}
var file_dm_whoami_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dm_whoami_proto_init() }
func file_dm_whoami_proto_init() {
	if File_dm_whoami_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dm_whoami_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dm_whoami_proto_goTypes,
		DependencyIndexes: file_dm_whoami_proto_depIdxs,
		MessageInfos:      file_dm_whoami_proto_msgTypes,
	}.Build()
	File_dm_whoami_proto = out.File
	file_dm_whoami_proto_rawDesc = nil
	file_dm_whoami_proto_goTypes = nil
	file_dm_whoami_proto_depIdxs = nil
}
