// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: TagmenuRequestApplyForOutdoor.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 申请文件出边界的请求
type TagmenuRequestApplyForOutdoor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePaths []*wrapperspb.StringValue `protobuf:"bytes,1,rep,name=file_paths,json=filePaths,proto3" json:"file_paths,omitempty"` // 指定的文件集合
	Remark    *wrapperspb.StringValue   `protobuf:"bytes,2,opt,name=remark,proto3,oneof" json:"remark,omitempty"`                  // 描述
}

func (x *TagmenuRequestApplyForOutdoor) Reset() {
	*x = TagmenuRequestApplyForOutdoor{}
	mi := &file_TagmenuRequestApplyForOutdoor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagmenuRequestApplyForOutdoor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagmenuRequestApplyForOutdoor) ProtoMessage() {}

func (x *TagmenuRequestApplyForOutdoor) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuRequestApplyForOutdoor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagmenuRequestApplyForOutdoor.ProtoReflect.Descriptor instead.
func (*TagmenuRequestApplyForOutdoor) Descriptor() ([]byte, []int) {
	return file_TagmenuRequestApplyForOutdoor_proto_rawDescGZIP(), []int{0}
}

func (x *TagmenuRequestApplyForOutdoor) GetFilePaths() []*wrapperspb.StringValue {
	if x != nil {
		return x.FilePaths
	}
	return nil
}

func (x *TagmenuRequestApplyForOutdoor) GetRemark() *wrapperspb.StringValue {
	if x != nil {
		return x.Remark
	}
	return nil
}

var File_TagmenuRequestApplyForOutdoor_proto protoreflect.FileDescriptor

var file_TagmenuRequestApplyForOutdoor_proto_rawDesc = []byte{
	0x0a, 0x23, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x46, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x70, 0x63, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x1d, 0x54,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x46, 0x6f, 0x72, 0x4f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x0a,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x39, 0x0a, 0x06, 0x72, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x42,
	0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TagmenuRequestApplyForOutdoor_proto_rawDescOnce sync.Once
	file_TagmenuRequestApplyForOutdoor_proto_rawDescData = file_TagmenuRequestApplyForOutdoor_proto_rawDesc
)

func file_TagmenuRequestApplyForOutdoor_proto_rawDescGZIP() []byte {
	file_TagmenuRequestApplyForOutdoor_proto_rawDescOnce.Do(func() {
		file_TagmenuRequestApplyForOutdoor_proto_rawDescData = protoimpl.X.CompressGZIP(file_TagmenuRequestApplyForOutdoor_proto_rawDescData)
	})
	return file_TagmenuRequestApplyForOutdoor_proto_rawDescData
}

var file_TagmenuRequestApplyForOutdoor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TagmenuRequestApplyForOutdoor_proto_goTypes = []any{
	(*TagmenuRequestApplyForOutdoor)(nil), // 0: docmap.protobuf.ipc.TagmenuRequestApplyForOutdoor
	(*wrapperspb.StringValue)(nil),        // 1: google.protobuf.StringValue
}
var file_TagmenuRequestApplyForOutdoor_proto_depIdxs = []int32{
	1, // 0: docmap.protobuf.ipc.TagmenuRequestApplyForOutdoor.file_paths:type_name -> google.protobuf.StringValue
	1, // 1: docmap.protobuf.ipc.TagmenuRequestApplyForOutdoor.remark:type_name -> google.protobuf.StringValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TagmenuRequestApplyForOutdoor_proto_init() }
func file_TagmenuRequestApplyForOutdoor_proto_init() {
	if File_TagmenuRequestApplyForOutdoor_proto != nil {
		return
	}
	file_TagmenuRequestApplyForOutdoor_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TagmenuRequestApplyForOutdoor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TagmenuRequestApplyForOutdoor_proto_goTypes,
		DependencyIndexes: file_TagmenuRequestApplyForOutdoor_proto_depIdxs,
		MessageInfos:      file_TagmenuRequestApplyForOutdoor_proto_msgTypes,
	}.Build()
	File_TagmenuRequestApplyForOutdoor_proto = out.File
	file_TagmenuRequestApplyForOutdoor_proto_rawDesc = nil
	file_TagmenuRequestApplyForOutdoor_proto_goTypes = nil
	file_TagmenuRequestApplyForOutdoor_proto_depIdxs = nil
}
