// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: TagmenuRequestWriteFileCategory.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文件类别
type FileCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath     *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`             // 文件路径
	CategoryCode *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"` // 级别代码
}

func (x *FileCategory) Reset() {
	*x = FileCategory{}
	mi := &file_TagmenuRequestWriteFileCategory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCategory) ProtoMessage() {}

func (x *FileCategory) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuRequestWriteFileCategory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCategory.ProtoReflect.Descriptor instead.
func (*FileCategory) Descriptor() ([]byte, []int) {
	return file_TagmenuRequestWriteFileCategory_proto_rawDescGZIP(), []int{0}
}

func (x *FileCategory) GetFilePath() *wrapperspb.StringValue {
	if x != nil {
		return x.FilePath
	}
	return nil
}

func (x *FileCategory) GetCategoryCode() *wrapperspb.StringValue {
	if x != nil {
		return x.CategoryCode
	}
	return nil
}

// 写指定文件的类别
type TagmenuRequestWriteFileCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileCategories []*FileCategory `protobuf:"bytes,1,rep,name=file_categories,json=fileCategories,proto3" json:"file_categories,omitempty"` // 指定的文件类别
}

func (x *TagmenuRequestWriteFileCategory) Reset() {
	*x = TagmenuRequestWriteFileCategory{}
	mi := &file_TagmenuRequestWriteFileCategory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagmenuRequestWriteFileCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagmenuRequestWriteFileCategory) ProtoMessage() {}

func (x *TagmenuRequestWriteFileCategory) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuRequestWriteFileCategory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagmenuRequestWriteFileCategory.ProtoReflect.Descriptor instead.
func (*TagmenuRequestWriteFileCategory) Descriptor() ([]byte, []int) {
	return file_TagmenuRequestWriteFileCategory_proto_rawDescGZIP(), []int{1}
}

func (x *TagmenuRequestWriteFileCategory) GetFileCategories() []*FileCategory {
	if x != nil {
		return x.FileCategories
	}
	return nil
}

var File_TagmenuRequestWriteFileCategory_proto protoreflect.FileDescriptor

var file_TagmenuRequestWriteFileCategory_proto_rawDesc = []byte{
	0x0a, 0x25, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x70, 0x63, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a,
	0x0c, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x39, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x41, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x6d, 0x0a, 0x1f, 0x54,
	0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x4a,
	0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0e, 0x66, 0x69, 0x6c, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f,
	0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TagmenuRequestWriteFileCategory_proto_rawDescOnce sync.Once
	file_TagmenuRequestWriteFileCategory_proto_rawDescData = file_TagmenuRequestWriteFileCategory_proto_rawDesc
)

func file_TagmenuRequestWriteFileCategory_proto_rawDescGZIP() []byte {
	file_TagmenuRequestWriteFileCategory_proto_rawDescOnce.Do(func() {
		file_TagmenuRequestWriteFileCategory_proto_rawDescData = protoimpl.X.CompressGZIP(file_TagmenuRequestWriteFileCategory_proto_rawDescData)
	})
	return file_TagmenuRequestWriteFileCategory_proto_rawDescData
}

var file_TagmenuRequestWriteFileCategory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TagmenuRequestWriteFileCategory_proto_goTypes = []any{
	(*FileCategory)(nil),                    // 0: docmap.protobuf.ipc.FileCategory
	(*TagmenuRequestWriteFileCategory)(nil), // 1: docmap.protobuf.ipc.TagmenuRequestWriteFileCategory
	(*wrapperspb.StringValue)(nil),          // 2: google.protobuf.StringValue
}
var file_TagmenuRequestWriteFileCategory_proto_depIdxs = []int32{
	2, // 0: docmap.protobuf.ipc.FileCategory.file_path:type_name -> google.protobuf.StringValue
	2, // 1: docmap.protobuf.ipc.FileCategory.category_code:type_name -> google.protobuf.StringValue
	0, // 2: docmap.protobuf.ipc.TagmenuRequestWriteFileCategory.file_categories:type_name -> docmap.protobuf.ipc.FileCategory
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TagmenuRequestWriteFileCategory_proto_init() }
func file_TagmenuRequestWriteFileCategory_proto_init() {
	if File_TagmenuRequestWriteFileCategory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TagmenuRequestWriteFileCategory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TagmenuRequestWriteFileCategory_proto_goTypes,
		DependencyIndexes: file_TagmenuRequestWriteFileCategory_proto_depIdxs,
		MessageInfos:      file_TagmenuRequestWriteFileCategory_proto_msgTypes,
	}.Build()
	File_TagmenuRequestWriteFileCategory_proto = out.File
	file_TagmenuRequestWriteFileCategory_proto_rawDesc = nil
	file_TagmenuRequestWriteFileCategory_proto_goTypes = nil
	file_TagmenuRequestWriteFileCategory_proto_depIdxs = nil
}
