// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: TagmenuResponseWriteFileCategory.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteFileCategoryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath   *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`          // 文件路径
	ResultCode *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`    // 写入结果（零：成功；其它：失败）
	ResultMsg  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=result_msg,json=resultMsg,proto3,oneof" json:"result_msg,omitempty"` // 失败信息
}

func (x *WriteFileCategoryResult) Reset() {
	*x = WriteFileCategoryResult{}
	mi := &file_TagmenuResponseWriteFileCategory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileCategoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileCategoryResult) ProtoMessage() {}

func (x *WriteFileCategoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuResponseWriteFileCategory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileCategoryResult.ProtoReflect.Descriptor instead.
func (*WriteFileCategoryResult) Descriptor() ([]byte, []int) {
	return file_TagmenuResponseWriteFileCategory_proto_rawDescGZIP(), []int{0}
}

func (x *WriteFileCategoryResult) GetFilePath() *wrapperspb.StringValue {
	if x != nil {
		return x.FilePath
	}
	return nil
}

func (x *WriteFileCategoryResult) GetResultCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.ResultCode
	}
	return nil
}

func (x *WriteFileCategoryResult) GetResultMsg() *wrapperspb.StringValue {
	if x != nil {
		return x.ResultMsg
	}
	return nil
}

// 写指定文件的类别的回应
type TagmenuResponseWriteFileCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*WriteFileCategoryResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // 读取到的结果清单
}

func (x *TagmenuResponseWriteFileCategory) Reset() {
	*x = TagmenuResponseWriteFileCategory{}
	mi := &file_TagmenuResponseWriteFileCategory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagmenuResponseWriteFileCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagmenuResponseWriteFileCategory) ProtoMessage() {}

func (x *TagmenuResponseWriteFileCategory) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuResponseWriteFileCategory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagmenuResponseWriteFileCategory.ProtoReflect.Descriptor instead.
func (*TagmenuResponseWriteFileCategory) Descriptor() ([]byte, []int) {
	return file_TagmenuResponseWriteFileCategory_proto_rawDescGZIP(), []int{1}
}

func (x *TagmenuResponseWriteFileCategory) GetResults() []*WriteFileCategoryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_TagmenuResponseWriteFileCategory_proto protoreflect.FileDescriptor

var file_TagmenuResponseWriteFileCategory_proto_rawDesc = []byte{
	0x0a, 0x26, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x70, 0x63, 0x1a, 0x1e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x01,
	0x0a, 0x17, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x12, 0x3c, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33,
	0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4d, 0x73,
	0x67, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f,
	0x6d, 0x73, 0x67, 0x22, 0x6a, 0x0a, 0x20, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x46, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x64, 0x6f, 0x63, 0x6d, 0x61,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x70, 0x63, 0x2e, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42,
	0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TagmenuResponseWriteFileCategory_proto_rawDescOnce sync.Once
	file_TagmenuResponseWriteFileCategory_proto_rawDescData = file_TagmenuResponseWriteFileCategory_proto_rawDesc
)

func file_TagmenuResponseWriteFileCategory_proto_rawDescGZIP() []byte {
	file_TagmenuResponseWriteFileCategory_proto_rawDescOnce.Do(func() {
		file_TagmenuResponseWriteFileCategory_proto_rawDescData = protoimpl.X.CompressGZIP(file_TagmenuResponseWriteFileCategory_proto_rawDescData)
	})
	return file_TagmenuResponseWriteFileCategory_proto_rawDescData
}

var file_TagmenuResponseWriteFileCategory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TagmenuResponseWriteFileCategory_proto_goTypes = []any{
	(*WriteFileCategoryResult)(nil),          // 0: docmap.protobuf.ipc.WriteFileCategoryResult
	(*TagmenuResponseWriteFileCategory)(nil), // 1: docmap.protobuf.ipc.TagmenuResponseWriteFileCategory
	(*wrapperspb.StringValue)(nil),           // 2: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),            // 3: google.protobuf.Int32Value
}
var file_TagmenuResponseWriteFileCategory_proto_depIdxs = []int32{
	2, // 0: docmap.protobuf.ipc.WriteFileCategoryResult.file_path:type_name -> google.protobuf.StringValue
	3, // 1: docmap.protobuf.ipc.WriteFileCategoryResult.result_code:type_name -> google.protobuf.Int32Value
	2, // 2: docmap.protobuf.ipc.WriteFileCategoryResult.result_msg:type_name -> google.protobuf.StringValue
	0, // 3: docmap.protobuf.ipc.TagmenuResponseWriteFileCategory.results:type_name -> docmap.protobuf.ipc.WriteFileCategoryResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_TagmenuResponseWriteFileCategory_proto_init() }
func file_TagmenuResponseWriteFileCategory_proto_init() {
	if File_TagmenuResponseWriteFileCategory_proto != nil {
		return
	}
	file_TagmenuResponseWriteFileCategory_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TagmenuResponseWriteFileCategory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TagmenuResponseWriteFileCategory_proto_goTypes,
		DependencyIndexes: file_TagmenuResponseWriteFileCategory_proto_depIdxs,
		MessageInfos:      file_TagmenuResponseWriteFileCategory_proto_msgTypes,
	}.Build()
	File_TagmenuResponseWriteFileCategory_proto = out.File
	file_TagmenuResponseWriteFileCategory_proto_rawDesc = nil
	file_TagmenuResponseWriteFileCategory_proto_goTypes = nil
	file_TagmenuResponseWriteFileCategory_proto_depIdxs = nil
}
