// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: TagmenuRequestRemoveFolderUserDatas.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 移除指定目录的标记
type TagmenuRequestRemoveFolderUserDatas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recursive *wrapperspb.BoolValue     `protobuf:"bytes,1,opt,name=recursive,proto3" json:"recursive,omitempty"` // 是否同时移除子目录的标记
	Dirs      []*wrapperspb.StringValue `protobuf:"bytes,2,rep,name=dirs,proto3" json:"dirs,omitempty"`           // 要移除标记的目录
}

func (x *TagmenuRequestRemoveFolderUserDatas) Reset() {
	*x = TagmenuRequestRemoveFolderUserDatas{}
	mi := &file_TagmenuRequestRemoveFolderUserDatas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagmenuRequestRemoveFolderUserDatas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagmenuRequestRemoveFolderUserDatas) ProtoMessage() {}

func (x *TagmenuRequestRemoveFolderUserDatas) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuRequestRemoveFolderUserDatas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagmenuRequestRemoveFolderUserDatas.ProtoReflect.Descriptor instead.
func (*TagmenuRequestRemoveFolderUserDatas) Descriptor() ([]byte, []int) {
	return file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescGZIP(), []int{0}
}

func (x *TagmenuRequestRemoveFolderUserDatas) GetRecursive() *wrapperspb.BoolValue {
	if x != nil {
		return x.Recursive
	}
	return nil
}

func (x *TagmenuRequestRemoveFolderUserDatas) GetDirs() []*wrapperspb.StringValue {
	if x != nil {
		return x.Dirs
	}
	return nil
}

var File_TagmenuRequestRemoveFolderUserDatas_proto protoreflect.FileDescriptor

var file_TagmenuRequestRemoveFolderUserDatas_proto_rawDesc = []byte{
	0x0a, 0x29, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x64, 0x6f, 0x63,
	0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x69, 0x70, 0x63,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x91, 0x01, 0x0a, 0x23, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75,
	0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f,
	0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69,
	0x76, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x69, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04,
	0x64, 0x69, 0x72, 0x73, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescOnce sync.Once
	file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescData = file_TagmenuRequestRemoveFolderUserDatas_proto_rawDesc
)

func file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescGZIP() []byte {
	file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescOnce.Do(func() {
		file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescData = protoimpl.X.CompressGZIP(file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescData)
	})
	return file_TagmenuRequestRemoveFolderUserDatas_proto_rawDescData
}

var file_TagmenuRequestRemoveFolderUserDatas_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TagmenuRequestRemoveFolderUserDatas_proto_goTypes = []any{
	(*TagmenuRequestRemoveFolderUserDatas)(nil), // 0: docmap.protobuf.ipc.TagmenuRequestRemoveFolderUserDatas
	(*wrapperspb.BoolValue)(nil),                // 1: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil),              // 2: google.protobuf.StringValue
}
var file_TagmenuRequestRemoveFolderUserDatas_proto_depIdxs = []int32{
	1, // 0: docmap.protobuf.ipc.TagmenuRequestRemoveFolderUserDatas.recursive:type_name -> google.protobuf.BoolValue
	2, // 1: docmap.protobuf.ipc.TagmenuRequestRemoveFolderUserDatas.dirs:type_name -> google.protobuf.StringValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TagmenuRequestRemoveFolderUserDatas_proto_init() }
func file_TagmenuRequestRemoveFolderUserDatas_proto_init() {
	if File_TagmenuRequestRemoveFolderUserDatas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TagmenuRequestRemoveFolderUserDatas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TagmenuRequestRemoveFolderUserDatas_proto_goTypes,
		DependencyIndexes: file_TagmenuRequestRemoveFolderUserDatas_proto_depIdxs,
		MessageInfos:      file_TagmenuRequestRemoveFolderUserDatas_proto_msgTypes,
	}.Build()
	File_TagmenuRequestRemoveFolderUserDatas_proto = out.File
	file_TagmenuRequestRemoveFolderUserDatas_proto_rawDesc = nil
	file_TagmenuRequestRemoveFolderUserDatas_proto_goTypes = nil
	file_TagmenuRequestRemoveFolderUserDatas_proto_depIdxs = nil
}
