// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0--rc3
// source: TagmenuResponseReadFileLevelAndCategory.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileLevelAndCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath     *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`             // 文件路径
	LevelCode    *wrapperspb.UInt32Value `protobuf:"bytes,2,opt,name=level_code,json=levelCode,proto3" json:"level_code,omitempty"`          // 安全级别代码(为零表示不存在)
	CategoryCode *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=category_code,json=categoryCode,proto3" json:"category_code,omitempty"` // 类别代码(为空表示未分类)
	AodCode      *wrapperspb.UInt32Value `protobuf:"bytes,4,opt,name=aod_code,json=aodCode,proto3" json:"aod_code,omitempty"`                // 允许外发(为零表示禁止，其它允许)
}

func (x *FileLevelAndCategory) Reset() {
	*x = FileLevelAndCategory{}
	mi := &file_TagmenuResponseReadFileLevelAndCategory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLevelAndCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLevelAndCategory) ProtoMessage() {}

func (x *FileLevelAndCategory) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuResponseReadFileLevelAndCategory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLevelAndCategory.ProtoReflect.Descriptor instead.
func (*FileLevelAndCategory) Descriptor() ([]byte, []int) {
	return file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescGZIP(), []int{0}
}

func (x *FileLevelAndCategory) GetFilePath() *wrapperspb.StringValue {
	if x != nil {
		return x.FilePath
	}
	return nil
}

func (x *FileLevelAndCategory) GetLevelCode() *wrapperspb.UInt32Value {
	if x != nil {
		return x.LevelCode
	}
	return nil
}

func (x *FileLevelAndCategory) GetCategoryCode() *wrapperspb.StringValue {
	if x != nil {
		return x.CategoryCode
	}
	return nil
}

func (x *FileLevelAndCategory) GetAodCode() *wrapperspb.UInt32Value {
	if x != nil {
		return x.AodCode
	}
	return nil
}

// 获取指定文件的级别和类别的回应
type TagmenuResponseReadFileLevelAndCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*FileLevelAndCategory `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"` // 读取到的结果清单
	Switch *wrapperspb.BoolValue   `protobuf:"bytes,2,opt,name=switch,proto3" json:"switch,omitempty"` // 显示右键菜单开关
}

func (x *TagmenuResponseReadFileLevelAndCategory) Reset() {
	*x = TagmenuResponseReadFileLevelAndCategory{}
	mi := &file_TagmenuResponseReadFileLevelAndCategory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagmenuResponseReadFileLevelAndCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagmenuResponseReadFileLevelAndCategory) ProtoMessage() {}

func (x *TagmenuResponseReadFileLevelAndCategory) ProtoReflect() protoreflect.Message {
	mi := &file_TagmenuResponseReadFileLevelAndCategory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagmenuResponseReadFileLevelAndCategory.ProtoReflect.Descriptor instead.
func (*TagmenuResponseReadFileLevelAndCategory) Descriptor() ([]byte, []int) {
	return file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescGZIP(), []int{1}
}

func (x *TagmenuResponseReadFileLevelAndCategory) GetResult() []*FileLevelAndCategory {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TagmenuResponseReadFileLevelAndCategory) GetSwitch() *wrapperspb.BoolValue {
	if x != nil {
		return x.Switch
	}
	return nil
}

var File_TagmenuResponseReadFileLevelAndCategory_proto protoreflect.FileDescriptor

var file_TagmenuResponseReadFileLevelAndCategory_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x41, 0x6e,
	0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x69, 0x70, 0x63, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x41, 0x6e, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x39, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x3b, 0x0a, 0x0a, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55,
	0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x41, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x61, 0x6f, 0x64, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x55, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x61, 0x6f, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0xa0, 0x01, 0x0a, 0x27, 0x54, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x75, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x41, 0x6e, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x41, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x69, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x41, 0x6e, 0x64,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x32, 0x0a, 0x06, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x73, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x64, 0x6f, 0x63, 0x6d, 0x61, 0x70,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescOnce sync.Once
	file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescData = file_TagmenuResponseReadFileLevelAndCategory_proto_rawDesc
)

func file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescGZIP() []byte {
	file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescOnce.Do(func() {
		file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescData = protoimpl.X.CompressGZIP(file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescData)
	})
	return file_TagmenuResponseReadFileLevelAndCategory_proto_rawDescData
}

var file_TagmenuResponseReadFileLevelAndCategory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TagmenuResponseReadFileLevelAndCategory_proto_goTypes = []any{
	(*FileLevelAndCategory)(nil),                    // 0: docmap.protobuf.ipc.FileLevelAndCategory
	(*TagmenuResponseReadFileLevelAndCategory)(nil), // 1: docmap.protobuf.ipc.TagmenuResponseReadFileLevelAndCategory
	(*wrapperspb.StringValue)(nil),                  // 2: google.protobuf.StringValue
	(*wrapperspb.UInt32Value)(nil),                  // 3: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),                    // 4: google.protobuf.BoolValue
}
var file_TagmenuResponseReadFileLevelAndCategory_proto_depIdxs = []int32{
	2, // 0: docmap.protobuf.ipc.FileLevelAndCategory.file_path:type_name -> google.protobuf.StringValue
	3, // 1: docmap.protobuf.ipc.FileLevelAndCategory.level_code:type_name -> google.protobuf.UInt32Value
	2, // 2: docmap.protobuf.ipc.FileLevelAndCategory.category_code:type_name -> google.protobuf.StringValue
	3, // 3: docmap.protobuf.ipc.FileLevelAndCategory.aod_code:type_name -> google.protobuf.UInt32Value
	0, // 4: docmap.protobuf.ipc.TagmenuResponseReadFileLevelAndCategory.result:type_name -> docmap.protobuf.ipc.FileLevelAndCategory
	4, // 5: docmap.protobuf.ipc.TagmenuResponseReadFileLevelAndCategory.switch:type_name -> google.protobuf.BoolValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_TagmenuResponseReadFileLevelAndCategory_proto_init() }
func file_TagmenuResponseReadFileLevelAndCategory_proto_init() {
	if File_TagmenuResponseReadFileLevelAndCategory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TagmenuResponseReadFileLevelAndCategory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TagmenuResponseReadFileLevelAndCategory_proto_goTypes,
		DependencyIndexes: file_TagmenuResponseReadFileLevelAndCategory_proto_depIdxs,
		MessageInfos:      file_TagmenuResponseReadFileLevelAndCategory_proto_msgTypes,
	}.Build()
	File_TagmenuResponseReadFileLevelAndCategory_proto = out.File
	file_TagmenuResponseReadFileLevelAndCategory_proto_rawDesc = nil
	file_TagmenuResponseReadFileLevelAndCategory_proto_goTypes = nil
	file_TagmenuResponseReadFileLevelAndCategory_proto_depIdxs = nil
}
